# Generated by Django 3.1.1 on 2021-02-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillname', models.CharField(max_length=30)),
                ('skillPercent', models.IntegerField(max_length=3)),
            ],
        ),
    ]
