# Generated by Django 3.1.6 on 2021-02-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('project_url', models.URLField(blank=True)),
                ('project_pic', models.ImageField(blank=True, upload_to='Project_pic')),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillPercent',
            field=models.IntegerField(),
        ),
    ]
