# Generated by Django 2.2.5 on 2021-02-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0003_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(upload_to='Project_pic'),
        ),
    ]
